package com.dependencyimpact.common.exceptions;

public enum ErrorCode {
    AUTHENTICATION_REQUIRED,
    INVALID_TOKEN,
    ACCESS_DENIED,
    SERVICE_NOT_FOUND,
    TEAM_NOT_FOUND,
    API_NOT_FOUND,
    DEPENDENCY_NOT_FOUND,
    TOPIC_NOT_FOUND,
    DATABASE_NOT_FOUND,
    DUPLICATE_SERVICE,
    DUPLICATE_DEPENDENCY,
    DUPLICATE_TOPIC,
    INVALID_REQUEST,
    VALIDATION_FAILED,
    GRAPH_TRAVERSAL_LIMIT_EXCEEDED,
    IMPACT_ANALYSIS_FAILED,
    IMPACT_ANALYSIS_NOT_FOUND,
    INCIDENT_NOT_FOUND,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE;
}
