apiVersion: v1
kind: Service
metadata:
  name: dependency-collector
  namespace: microservice-impact
spec:
  selector:
    app: dependency-collector
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
