apiVersion: v1
kind: Service
metadata:
  name: impact-analysis-service
  namespace: microservice-impact
spec:
  selector:
    app: impact-analysis-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
