apiVersion: v1
kind: Service
metadata:
  name: runtime-analysis-service
  namespace: microservice-impact
spec:
  selector:
    app: runtime-analysis-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
