apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: microservice-impact
spec:
  selector:
    app: service-registry
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
