package com.dependencyimpact.common.events;

public enum EventType {
    DEPENDENCY_DISCOVERED,
    DEPENDENCY_UPDATED,
    DEPENDENCY_REMOVED,
    SERVICE_REGISTERED,
    SERVICE_UPDATED,
    SERVICE_STATUS_CHANGED,
    SERVICE_DECOMMISSIONED,
    RUNTIME_OBSERVATION_RECEIVED,
    IMPACT_ANALYSIS_REQUESTED,
    IMPACT_ANALYSIS_STARTED,
    IMPACT_ANALYSIS_COMPLETED,
    IMPACT_ANALYSIS_FAILED,
    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    INCIDENT_ANALYSIS_REQUESTED,
    INCIDENT_RESOLVED,
    NOTIFICATION_REQUESTED;
}
